import {
  Activity,
  AppWindow,
  Archive,
  BellRing,
  Box,
  Boxes,
  Clock,
  Cloud,
  Container,
  Cpu,
  CreditCard,
  Database,
  FileCode,
  FileCog,
  Globe,
  HardDrive,
  Inbox,
  KeyRound,
  Laptop,
  Layers,
  ListOrdered,
  Lock,
  Mail,
  MemoryStick,
  Monitor,
  Network,
  Orbit,
  Package,
  Play,
  Radio,
  Rocket,
  Route,
  Search,
  Server,
  ShieldCheck,
  Smartphone,
  Split,
  SquareDashed,
  Table2,
  Timer,
  User,
  UserRoundCheck,
  Waypoints,
  Webhook,
  Workflow,
  Zap,
} from "lucide";
import {
  siAngular,
  siApachecassandra,
  siApachekafka,
  siArgo,
  siAuth0,
  siBun,
  siClerk,
  siClickhouse,
  siCloudflare,
  siCockroachlabs,
  siContainerd,
  siDatadog,
  siDjango,
  siDocker,
  siDotnet,
  siElasticsearch,
  siExpress,
  siFastapi,
  siFirebase,
  siFlutter,
  siGithubactions,
  siGo,
  siGooglebigquery,
  siGooglecloud,
  siGooglecloudspanner,
  siGooglecloudstorage,
  siGrafana,
  siGraphql,
  siHelm,
  siIstio,
  siKubernetes,
  siLaravel,
  siMariadb,
  siMongodb,
  siMysql,
  siNatsdotio,
  siNeo4j,
  siNestjs,
  siNextdotjs,
  siNginx,
  siNodedotjs,
  siOkta,
  siPodman,
  siPostgresql,
  siPrometheus,
  siPython,
  siRabbitmq,
  siReact,
  siRedis,
  siRubyonrails,
  siRust,
  siSentry,
  siSnowflake,
  siSpring,
  siSqlite,
  siStripe,
  siSupabase,
  siSvelte,
  siTailwindcss,
  siTerraform,
  siTypescript,
  siVite,
  siVuedotjs,
} from "simple-icons";

import type { ComponentItem, ComponentProvider } from "@/editor/component-catalog";
import { brand, glyph, type IconSpec, monogram } from "@/editor/icons";

/** An item drawn with a line icon in its provider's colour. */
const g = (id: string, label: string, node: Parameters<typeof glyph>[0], keywords?: string) =>
  ({ id, label, icon: glyph(node), keywords }) satisfies ComponentItem;

/** An item drawn with its own brand logo and colour. */
const b = (id: string, label: string, si: { path: string; hex: string }, keywords?: string) => {
  const icon = brand(si) as Extract<IconSpec, { kind: "brand" }>;
  return { id, label, icon, color: icon.hex, keywords } satisfies ComponentItem;
};

// AWS and Azure ask icon sets not to ship their logos, so they get a lettered badge in their brand
// colour, and their services get line icons. Their official architecture icon sets can still be
// put on a board as images.

export const BUILT_IN_PROVIDERS: ComponentProvider[] = [
  {
    id: "aws",
    label: "AWS",
    color: "#ff9900",
    logo: monogram("aws"),
    items: [
      g("ec2", "EC2", Server, "compute vm instance"),
      g("lambda", "Lambda", Zap, "function serverless"),
      g("s3", "S3", Archive, "storage bucket object"),
      g("rds", "RDS", Database, "sql postgres mysql"),
      g("dynamodb", "DynamoDB", Table2, "nosql table"),
      g("sqs", "SQS", Inbox, "queue messages"),
      g("sns", "SNS", BellRing, "notifications pubsub topic"),
      g("api-gateway", "API Gateway", Waypoints, "rest http"),
      g("cloudfront", "CloudFront", Globe, "cdn edge"),
      g("elb", "Load Balancer", Split, "alb nlb elb"),
      g("ecs", "ECS", Container, "containers fargate"),
      g("eks", "EKS", Boxes, "kubernetes"),
      g("route53", "Route 53", Route, "dns"),
      g("cognito", "Cognito", UserRoundCheck, "auth users"),
      g("step-functions", "Step Functions", Workflow, "workflow orchestration"),
      g("eventbridge", "EventBridge", Radio, "events bus"),
      g("elasticache", "ElastiCache", MemoryStick, "cache redis"),
      g("cloudwatch", "CloudWatch", Activity, "monitoring logs metrics"),
      g("ses", "SES", Mail, "email"),
      g("iam", "IAM", KeyRound, "roles permissions"),
    ],
  },
  {
    id: "azure",
    label: "Azure",
    color: "#0078d4",
    logo: monogram("Az"),
    items: [
      g("vm", "Virtual Machine", Server, "compute"),
      g("functions", "Functions", Zap, "serverless"),
      g("app-service", "App Service", AppWindow, "web app"),
      g("aks", "AKS", Boxes, "kubernetes"),
      g("container-apps", "Container Apps", Container, "containers"),
      g("blob", "Blob Storage", Archive, "storage"),
      g("sql", "SQL Database", Database, "sql server"),
      g("cosmos", "Cosmos DB", Orbit, "nosql"),
      g("service-bus", "Service Bus", Inbox, "queue messages"),
      g("event-grid", "Event Grid", Radio, "events"),
      g("api-management", "API Management", Waypoints, "apim gateway"),
      g("front-door", "Front Door", Globe, "cdn edge"),
      g("entra", "Entra ID", KeyRound, "active directory auth"),
      g("key-vault", "Key Vault", Lock, "secrets"),
      g("monitor", "Monitor", Activity, "logs metrics insights"),
    ],
  },
  {
    id: "gcp",
    label: "Google Cloud",
    color: "#4285f4",
    logo: brand(siGooglecloud),
    items: [
      g("compute-engine", "Compute Engine", Server, "vm"),
      g("cloud-run", "Cloud Run", Play, "containers serverless"),
      g("functions", "Cloud Functions", Zap, "serverless"),
      g("gke", "GKE", Boxes, "kubernetes"),
      b("storage", "Cloud Storage", siGooglecloudstorage, "bucket gcs"),
      g("cloud-sql", "Cloud SQL", Database, "postgres mysql"),
      b("spanner", "Spanner", siGooglecloudspanner, "database"),
      b("bigquery", "BigQuery", siGooglebigquery, "warehouse analytics"),
      g("pubsub", "Pub/Sub", Radio, "messages events"),
      g("memorystore", "Memorystore", MemoryStick, "cache redis"),
      g("load-balancing", "Load Balancing", Split, "lb"),
      b("firebase", "Firebase", siFirebase, "auth firestore"),
    ],
  },
  {
    id: "docker",
    label: "Docker",
    color: `#${siDocker.hex}`,
    logo: brand(siDocker),
    items: [
      b("docker", "Docker", siDocker),
      g("container", "Container", Container),
      g("image", "Image", Layers),
      g("volume", "Volume", HardDrive, "storage"),
      g("network", "Network", Network),
      g("compose", "Compose", FileCode, "docker-compose"),
      g("registry", "Registry", Package, "hub"),
      b("podman", "Podman", siPodman),
      b("containerd", "containerd", siContainerd),
    ],
  },
  {
    id: "k8s",
    label: "Kubernetes",
    color: `#${siKubernetes.hex}`,
    logo: brand(siKubernetes),
    items: [
      b("cluster", "Cluster", siKubernetes, "k8s"),
      g("pod", "Pod", Box),
      g("deployment", "Deployment", Layers),
      g("service", "Service", Waypoints, "svc"),
      g("ingress", "Ingress", Globe),
      g("statefulset", "StatefulSet", Database),
      g("job", "Job", Timer, "cronjob"),
      g("configmap", "ConfigMap", FileCog, "config"),
      g("secret", "Secret", KeyRound),
      g("namespace", "Namespace", SquareDashed, "ns"),
      g("node", "Node", Cpu),
      b("helm", "Helm", siHelm, "chart"),
      b("istio", "Istio", siIstio, "service mesh"),
      b("argo", "Argo CD", siArgo, "gitops"),
    ],
  },
  {
    id: "database",
    label: "Databases",
    color: "#336791",
    logo: glyph(Database),
    items: [
      b("postgres", "PostgreSQL", siPostgresql, "sql"),
      b("mysql", "MySQL", siMysql, "sql"),
      b("mariadb", "MariaDB", siMariadb, "sql"),
      b("sqlite", "SQLite", siSqlite, "sql"),
      b("mongodb", "MongoDB", siMongodb, "nosql document"),
      b("redis", "Redis", siRedis, "cache"),
      b("elasticsearch", "Elasticsearch", siElasticsearch, "search"),
      b("cassandra", "Cassandra", siApachecassandra, "nosql"),
      b("cockroach", "CockroachDB", siCockroachlabs, "sql distributed"),
      b("clickhouse", "ClickHouse", siClickhouse, "analytics olap"),
      b("snowflake", "Snowflake", siSnowflake, "warehouse"),
      b("neo4j", "Neo4j", siNeo4j, "graph"),
      b("supabase", "Supabase", siSupabase, "postgres"),
      g("database", "Database", Database, "generic"),
    ],
  },
  {
    id: "frontend",
    label: "Frontend",
    color: "#e8489a",
    logo: glyph(Monitor),
    items: [
      g("browser", "Web App", AppWindow, "browser spa"),
      g("mobile", "Mobile App", Smartphone, "ios android"),
      b("react", "React", siReact),
      b("nextjs", "Next.js", siNextdotjs),
      b("vue", "Vue", siVuedotjs),
      b("angular", "Angular", siAngular),
      b("svelte", "Svelte", siSvelte),
      b("flutter", "Flutter", siFlutter, "mobile"),
      b("typescript", "TypeScript", siTypescript),
      b("tailwind", "Tailwind CSS", siTailwindcss, "css"),
      b("vite", "Vite", siVite, "bundler"),
    ],
  },
  {
    id: "backend",
    label: "Backend",
    color: "#12a594",
    logo: glyph(Server),
    items: [
      g("api", "API", Webhook, "service rest"),
      g("worker", "Worker", Cpu, "job background"),
      b("node", "Node.js", siNodedotjs),
      b("go", "Go", siGo, "golang"),
      b("rust", "Rust", siRust),
      b("python", "Python", siPython),
      b("dotnet", ".NET", siDotnet, "csharp c#"),
      b("spring", "Spring", siSpring, "java"),
      b("django", "Django", siDjango, "python"),
      b("fastapi", "FastAPI", siFastapi, "python"),
      b("express", "Express", siExpress, "node"),
      b("nestjs", "NestJS", siNestjs, "node"),
      b("laravel", "Laravel", siLaravel, "php"),
      b("rails", "Rails", siRubyonrails, "ruby"),
      b("bun", "Bun", siBun),
      b("graphql", "GraphQL", siGraphql, "api"),
    ],
  },
  {
    id: "messaging",
    label: "Messaging",
    color: "#8e4ec6",
    logo: glyph(Inbox),
    items: [
      b("kafka", "Kafka", siApachekafka, "stream events"),
      b("rabbitmq", "RabbitMQ", siRabbitmq, "queue amqp"),
      b("nats", "NATS", siNatsdotio, "pubsub"),
      g("queue", "Queue", ListOrdered),
      g("topic", "Topic", Radio, "pubsub events"),
      g("webhook", "Webhook", Webhook),
    ],
  },
  {
    id: "ops",
    label: "Infra & Ops",
    color: "#5e5f66",
    logo: glyph(Activity),
    items: [
      b("nginx", "Nginx", siNginx, "proxy load balancer"),
      b("cloudflare", "Cloudflare", siCloudflare, "cdn dns"),
      b("terraform", "Terraform", siTerraform, "iac"),
      b("github-actions", "GitHub Actions", siGithubactions, "ci cd"),
      b("prometheus", "Prometheus", siPrometheus, "metrics"),
      b("grafana", "Grafana", siGrafana, "dashboards"),
      b("datadog", "Datadog", siDatadog, "monitoring"),
      b("sentry", "Sentry", siSentry, "errors"),
    ],
  },
  {
    id: "saas",
    label: "Auth & Payments",
    color: "#635bff",
    logo: glyph(ShieldCheck),
    items: [
      b("stripe", "Stripe", siStripe, "payments"),
      b("auth0", "Auth0", siAuth0, "auth"),
      b("okta", "Okta", siOkta, "auth sso"),
      b("clerk", "Clerk", siClerk, "auth"),
      g("payments", "Payments", CreditCard),
      g("email", "Email", Mail, "smtp"),
    ],
  },
  {
    id: "generic",
    label: "General",
    color: "#4a4a52",
    logo: glyph(Box),
    items: [
      g("user", "User", User, "person actor"),
      g("client", "Client", Laptop, "desktop"),
      g("server", "Server", Server),
      g("load-balancer", "Load Balancer", Split, "lb"),
      g("cache", "Cache", MemoryStick),
      g("storage", "Storage", HardDrive, "disk"),
      g("cron", "Scheduler", Clock, "cron"),
      g("firewall", "Firewall", ShieldCheck, "security"),
      g("internet", "Internet", Cloud, "cloud"),
      g("search", "Search", Search),
      g("deploy", "Deploy", Rocket, "release"),
    ],
  },
];
